apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  # type: ClusterIP # for Internal
  type: LoadBalancer
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 80      # External port
      targetPort: 8080  # Internal container port